web:
  command: sh -c "rails s --bind 0.0.0.0"
  ports:
    - "3000:3000"
  build: .
  volumes:
    - .:/app
  links:
    - redis:redis.local
    - mongodb:mongo.local
  environment:
    - REDIS_URL=redis://redis.local/0
    - MONGODB_HOST=mongo.local
    - CLIENT_ID=a22c62496f6c7d520782
    - CLIENT_SECRET=9e01f90cfca708c1ca00401635fcf9500aa3b6b2
    - SLAVES=

sidekiq:
  command: bundle exec sidekiq
  build: .
  volumes:
    - .:/app
  links:
    - redis:redis.local
    - mongodb:mongo.local
  environment:
    - REDIS_URL=redis://redis.local/0
    - MONGODB_HOST=mongo.local
    - CLIENT_ID=a22c62496f6c7d520782
    - CLIENT_SECRET=9e01f90cfca708c1ca00401635fcf9500aa3b6b2
    - SLAVES=

redis:
  image: redis:3.2

mongodb:
  image: mongo:3.3
